server:
  port: 9000

spring:
  application:
    name: bank

  profiles:
    active: local # Or prod based on your environment

# Configuration for the local profile
---
spring.config.activate.on-profile: local

spring:
  datasource:
    url: jdbc:h2:mem:bank
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  h2:
    console:
      enabled: true

  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

# Configuration for the prod profile
---
spring.config.activate.on-profile: prod

spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:mysql://mysql-java-hsachok-test1.g.aivencloud.com:27453/bank?sessionVariables=sql_require_primary_key=OFF
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: avnadmin
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
